apiVersion: autoscaling/v1 # Perfomence 85 we have autoscaling nodes
kind: HorizontalPodAutoscaler
metadata:
  name: devops-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: eSchool 
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 85
---
apiVersion: v1 #Add Load Balancer
kind: Service
metadata:
  name: eSchool
  labels:
    app: devops
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: devops
    tier: frontend
 
---
apiVersion: apps/v1beta1 #Build Docker Image
kind: Deployment
metadata:
  name: eSchool
  labels:
    app: devops
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops
      tier: frontend
  template:
    metadata:
      labels:
        app: devops
        tier: frontend
    spec:
      containers:
      - name: eSchool #image name
        image: gcr.io/devops-project-233717/devops-demo:0.0.1 #DO not use latest version
        ports:
        - containerPort: 8080

---